language: 'zh-CN'
startupDelay: 64
startupCycle: 14400
paths:
  updatePath: './plugins/update'
  tempPath: './plugins/AutoUpdatePlugins/temp'
  filePath: './plugins'
enablePreviousUpdate: true
zipFileCheck: true
zipFileCheckPattern: '\.(?:jar|zip)$'
ignoreDuplicates: true
sslVerify: true
proxy:
  type: DIRECT
  host: '127.0.0.1'
  port: 7890
setRequestProperty:
  - name: 'User-Agent'
    value: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
logLevel:
  - 'DEBUG'
  - 'MARK'
  - 'INFO'
  - 'WARN'
  - 'NET_WARN'
